import React, { useState, useEffect } from 'react';
import { AlertTriangle, Bell, Calendar, User, CheckCircle, Clock, FileText, UserX, DollarSign, Shield, Search, Filter, MoreVertical, Eye, Archive, Trash2, RefreshCw, Settings, Download, Send, Plus, X, Check } from 'lucide-react';

const HRAlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterPriority, setFilterPriority] = useState('all');
  const [filterType, setFilterType] = useState('all');
  const [filterStatus, setFilterStatus] = useState('active');
  const [selectedAlerts, setSelectedAlerts] = useState([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [stats, setStats] = useState({});
  const [viewMode, setViewMode] = useState('list'); // list, cards

  useEffect(() => {
    loadAlerts();
  }, []);

  const loadAlerts = async () => {
    try {
      const mockAlerts = [
        {
          id: 1,
          type: 'contract_expiry',
          category: 'Contrats',
          title: 'Contrats arrivant à expiration',
          message: 'Le contrat de Jean Dupont expire dans 30 jours (15 février 2024)',
          priority: 'high',
          status: 'active',
          date: new Date().toISOString(),
          dueDate: '2024-02-15',
          employee: 'Jean Dupont',
          employeeId: 1,
          department: 'Développement',
          assignedTo: 'Marie Dupont',
          createdBy: 'Système',
          actions: ['Renouveler contrat', 'Programmer entretien', 'Préparer documents'],
          relatedDocuments: ['Contrat_Jean_Dupont.pdf'],
          autoGenerated: true
        },
        {
          id: 2,
          type: 'leave_request',
          category: 'Congés',
          title: 'Demandes de congé en attente',
          message: '3 demandes de congé nécessitent votre approbation urgente',
          priority: 'medium',
          status: 'active',
          date: new Date(Date.now() - 86400000).toISOString(),
          dueDate: new Date(Date.now() + 172800000).toISOString(),
          count: 3,
          department: 'Multiple',
          assignedTo: 'Sophie Bernard',
          createdBy: 'Workflow',
          actions: ['Approuver', 'Rejeter', 'Demander plus d\'infos'],
          relatedDocuments: ['Demandes_Conges_Janvier.pdf'],
          autoGenerated: true
        },
        {
          id: 3,
          type: 'document_missing',
          category: 'Documents',
          title: 'Documents manquants',
          message: 'Marie Martin n\'a pas fourni tous les documents requis pour son dossier',
          priority: 'medium',
          status: 'active',
          date: new Date(Date.now() - 172800000).toISOString(),
          dueDate: new Date(Date.now() + 604800000).toISOString(),
          employee: 'Marie Martin',
          employeeId: 2,
          department: 'Marketing',
          assignedTo: 'Pierre Moreau',
          createdBy: 'Marie Dupont',
          actions: ['Relancer employé', 'Programmer RDV', 'Marquer comme résolu'],
          relatedDocuments: [],
          autoGenerated: false
        },
        {
          id: 4,
          type: 'performance_review',
          category: 'Évaluations',
          title: 'Évaluations annuelles en retard',
          message: '5 évaluations annuelles n\'ont pas été réalisées dans les délais',
          priority: 'high',
          status: 'active',
          date: new Date(Date.now() - 259200000).toISOString(),
          dueDate: new Date(Date.now() + 86400000).toISOString(),
          count: 5,
          department: 'Multiple',
          assignedTo: 'Thomas Dubois',
          createdBy: 'Système',
          actions: ['Programmer évaluations', 'Relancer managers', 'Reporter échéance'],
          relatedDocuments: ['Planning_Evaluations_2024.xlsx'],
          autoGenerated: true
        },
        {
          id: 5,
          type: 'training_due',
          category: 'Formation',
          title: 'Formations obligatoires expirées',
          message: 'La formation sécurité de 8 employés a expiré et doit être renouvelée',
          priority: 'high',
          status: 'active',
          date: new Date(Date.now() - 432000000).toISOString(),
          dueDate: new Date(Date.now() + 259200000).toISOString(),
          count: 8,
          department: 'Multiple',
          assignedTo: 'Emma Rousseau',
          createdBy: 'Système',
          actions: ['Programmer formations', 'Contacter formateur', 'Mettre à jour planning'],
          relatedDocuments: ['Liste_Formations_Expirees.pdf'],
          autoGenerated: true
        },
        {
          id: 6,
          type: 'salary_anomaly',
          category: 'Paie',
          title: 'Anomalie détectée dans la paie',
          message: 'Différence inhabituelle détectée dans le calcul de paie de janvier 2024',
          priority: 'high',
          status: 'active',
          date: new Date(Date.now() - 86400000).toISOString(),
          dueDate: new Date(Date.now() + 172800000).toISOString(),
          department: 'Finance',
          assignedTo: 'Pierre Moreau',
          createdBy: 'Système de paie',
          actions: ['Vérifier calculs', 'Corriger anomalie', 'Valider paie'],
          relatedDocuments: ['Rapport_Anomalies_Paie_Jan2024.pdf'],
          autoGenerated: true
        },
        {
          id: 7,
          type: 'compliance_check',
          category: 'Conformité',
          title: 'Audit de conformité requis',
          message: 'Audit trimestriel de conformité RH à effectuer avant fin janvier',
          priority: 'medium',
          status: 'active',
          date: new Date(Date.now() - 604800000).toISOString(),
          dueDate: '2024-01-31',
          department: 'RH',
          assignedTo: 'Marie Dupont',
          createdBy: 'Calendrier automatique',
          actions: ['Préparer audit', 'Rassembler documents', 'Planifier réunion'],
          relatedDocuments: ['Checklist_Audit_Q1_2024.pdf'],
          autoGenerated: true
        },
        {
          id: 8,
          type: 'absence_pattern',
          category: 'Présence',
          title: 'Schéma d\'absence inhabituel',
          message: 'Luc Bernard présente un schéma d\'absence récurrent les lundis',
          priority: 'low',
          status: 'active',
          date: new Date(Date.now() - 1209600000).toISOString(),
          dueDate: new Date(Date.now() + 604800000).toISOString(),
          employee: 'Luc Bernard',
          employeeId: 3,
          department: 'Ventes',
          assignedTo: 'Sophie Bernard',
          createdBy: 'Analyse automatique',
          actions: ['Discuter avec employé', 'Analyser causes', 'Proposer solutions'],
          relatedDocuments: ['Rapport_Absences_Luc_Bernard.pdf'],
          autoGenerated: true
        }
      ];
      
      setAlerts(mockAlerts);
      
      // Calculer les statistiques
      const activeAlerts = mockAlerts.filter(a => a.status === 'active');
      const highPriority = activeAlerts.filter(a => a.priority === 'high').length;
      const mediumPriority = activeAlerts.filter(a => a.priority === 'medium').length;
      const lowPriority = activeAlerts.filter(a => a.priority === 'low').length;
      const overdue = activeAlerts.filter(a => new Date(a.dueDate) < new Date()).length;
      
      setStats({
        total: activeAlerts.length,
        high: highPriority,
        medium: mediumPriority,
        low: lowPriority,
        overdue: overdue,
        resolved: mockAlerts.filter(a => a.status === 'resolved').length,
        autoGenerated: mockAlerts.filter(a => a.autoGenerated).length
      });
    } catch (error) {
      console.error('Erreur chargement alertes:', error);
    } finally {
      setLoading(false);
    }
  };

  const filteredAlerts = alerts.filter(alert => {
    const matchesSearch = alert.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         alert.message.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         alert.employee?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         alert.department.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesPriority = filterPriority === 'all' || alert.priority === filterPriority;
    const matchesType = filterType === 'all' || alert.type === filterType;
    const matchesStatus = filterStatus === 'all' || alert.status === filterStatus;
    return matchesSearch && matchesPriority && matchesType && matchesStatus;
  });

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'high': return 'bg-red-100 text-red-800 border-red-200';
      case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'low': return 'bg-blue-100 text-blue-800 border-blue-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  const getIcon = (type) => {
    switch (type) {
      case 'contract_expiry': return Calendar;
      case 'leave_request': return User;
      case 'document_missing': return FileText;
      case 'performance_review': return CheckCircle;
      case 'training_due': return Shield;
      case 'salary_anomaly': return DollarSign;
      case 'compliance_check': return Shield;
      case 'absence_pattern': return UserX;
      default: return Bell;
    }
  };

  const getTypeLabel = (type) => {
    const labels = {
      contract_expiry: 'Expiration contrat',
      leave_request: 'Demande congé',
      document_missing: 'Document manquant',
      performance_review: 'Évaluation',
      training_due: 'Formation',
      salary_anomaly: 'Anomalie paie',
      compliance_check: 'Conformité',
      absence_pattern: 'Absence'
    };
    return labels[type] || type;
  };

  const handleAlertAction = (alertId, action) => {
    console.log(`Action "${action}" sur l'alerte ${alertId}`);
    // Implémenter les actions spécifiques
  };

  const handleBulkAction = (action) => {
    console.log(`Action en lot "${action}" sur ${selectedAlerts.length} alertes`);
    setSelectedAlerts([]);
  };

  const isOverdue = (dueDate) => {
    return new Date(dueDate) < new Date();
  };

  const CreateAlertModal = ({ isOpen, onClose, onSubmit }) => {
    const [formData, setFormData] = useState({
      title: '',
      message: '',
      priority: 'medium',
      type: 'document_missing',
      assignedTo: '',
      dueDate: '',
      department: ''
    });

    if (!isOpen) return null;

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div className="bg-white rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold">Créer une nouvelle alerte</h2>
            <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg">
              <X className="w-5 h-5" />
            </button>
          </div>
          <form onSubmit={(e) => { e.preventDefault(); onSubmit(formData); }} className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">Titre de l'alerte</label>
              <input
                type="text"
                value={formData.title}
                onChange={(e) => setFormData({...formData, title: e.target.value})}
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Message</label>
              <textarea
                value={formData.message}
                onChange={(e) => setFormData({...formData, message: e.target.value})}
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                rows={3}
                required
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2">Priorité</label>
                <select
                  value={formData.priority}
                  onChange={(e) => setFormData({...formData, priority: e.target.value})}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                >
                  <option value="low">Faible</option>
                  <option value="medium">Moyenne</option>
                  <option value="high">Haute</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-2">Type</label>
                <select
                  value={formData.type}
                  onChange={(e) => setFormData({...formData, type: e.target.value})}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                >
                  <option value="document_missing">Document manquant</option>
                  <option value="contract_expiry">Expiration contrat</option>
                  <option value="leave_request">Demande congé</option>
                  <option value="performance_review">Évaluation</option>
                  <option value="training_due">Formation</option>
                  <option value="compliance_check">Conformité</option>
                </select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2">Assigné à</label>
                <input
                  type="text"
                  value={formData.assignedTo}
                  onChange={(e) => setFormData({...formData, assignedTo: e.target.value})}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-2">Département</label>
                <input
                  type="text"
                  value={formData.department}
                  onChange={(e) => setFormData({...formData, department: e.target.value})}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Échéance</label>
              <input
                type="date"
                value={formData.dueDate}
                onChange={(e) => setFormData({...formData, dueDate: e.target.value})}
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div className="flex justify-end space-x-3 pt-4">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-gray-600 border rounded-lg hover:bg-gray-50"
              >
                Annuler
              </button>
              <button
                type="submit"
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Créer l'alerte
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <Bell className="w-8 h-8 text-blue-600" />
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Centre d'Alertes RH</h1>
            <p className="text-gray-600">Gestion centralisée des notifications et alertes</p>
          </div>
        </div>
        <div className="flex items-center space-x-3">
          <button
            onClick={() => loadAlerts()}
            className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg"
            title="Actualiser"
          >
            <RefreshCw className="w-5 h-5" />
          </button>
          <button
            onClick={() => setShowCreateModal(true)}
            className="bg-blue-600 text-white px-4 py-2 rounded-lg flex items-center space-x-2 hover:bg-blue-700"
          >
            <Plus className="w-4 h-4" />
            <span>Nouvelle alerte</span>
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Alertes Actives</p>
              <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
            </div>
            <Bell className="w-8 h-8 text-blue-600" />
          </div>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Priorité Haute</p>
              <p className="text-2xl font-bold text-red-600">{stats.high}</p>
            </div>
            <AlertTriangle className="w-8 h-8 text-red-600" />
          </div>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">En Retard</p>
              <p className="text-2xl font-bold text-orange-600">{stats.overdue}</p>
            </div>
            <Clock className="w-8 h-8 text-orange-600" />
          </div>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Résolues</p>
              <p className="text-2xl font-bold text-green-600">{stats.resolved}</p>
            </div>
            <CheckCircle className="w-8 h-8 text-green-600" />
          </div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0">
          <div className="flex flex-col sm:flex-row sm:items-center space-y-3 sm:space-y-0 sm:space-x-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Rechercher une alerte..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 w-64"
              />
            </div>
            <select
              value={filterPriority}
              onChange={(e) => setFilterPriority(e.target.value)}
              className="px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">Toutes priorités</option>
              <option value="high">Haute</option>
              <option value="medium">Moyenne</option>
              <option value="low">Faible</option>
            </select>
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">Tous types</option>
              <option value="contract_expiry">Contrats</option>
              <option value="leave_request">Congés</option>
              <option value="document_missing">Documents</option>
              <option value="performance_review">Évaluations</option>
              <option value="training_due">Formations</option>
              <option value="salary_anomaly">Paie</option>
            </select>
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
              className="px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="active">Actives</option>
              <option value="resolved">Résolues</option>
              <option value="all">Toutes</option>
            </select>
          </div>
          
          <div className="flex items-center space-x-3">
            {selectedAlerts.length > 0 && (
              <div className="flex items-center space-x-2">
                <span className="text-sm text-gray-600">{selectedAlerts.length} sélectionnée(s)</span>
                <button
                  onClick={() => handleBulkAction('resolve')}
                  className="px-3 py-1 bg-green-600 text-white rounded text-sm hover:bg-green-700"
                >
                  Résoudre
                </button>
                <button
                  onClick={() => handleBulkAction('archive')}
                  className="px-3 py-1 bg-gray-600 text-white rounded text-sm hover:bg-gray-700"
                >
                  Archiver
                </button>
              </div>
            )}
            <div className="text-sm text-gray-600">
              {filteredAlerts.length} alerte(s) affichée(s)
            </div>
          </div>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => {
          const IconComponent = getIcon(alert.type);
          const isSelected = selectedAlerts.includes(alert.id);
          const alertOverdue = isOverdue(alert.dueDate);
          
          return (
            <div key={alert.id} className={`bg-white rounded-xl shadow-sm border p-6 hover:shadow-lg transition-shadow ${
              isSelected ? 'border-blue-500 bg-blue-50' : 'border-gray-100'
            } ${alertOverdue ? 'border-l-4 border-l-red-500' : ''}`}>
              <div className="flex items-start justify-between">
                <div className="flex items-start space-x-4 flex-1">
                  <input
                    type="checkbox"
                    checked={isSelected}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setSelectedAlerts([...selectedAlerts, alert.id]);
                      } else {
                        setSelectedAlerts(selectedAlerts.filter(id => id !== alert.id));
                      }
                    }}
                    className="mt-1"
                  />
                  <div className="p-3 bg-gray-100 rounded-lg">
                    <IconComponent className="w-6 h-6 text-gray-600" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center space-x-3 mb-2">
                      <h3 className="text-lg font-semibold text-gray-900">{alert.title}</h3>
                      <span className={`px-2 py-1 rounded-full text-xs font-medium border ${getPriorityColor(alert.priority)}`}>
                        {alert.priority === 'high' ? 'Urgent' : alert.priority === 'medium' ? 'Moyen' : 'Faible'}
                      </span>
                      <span className="px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-700">
                        {getTypeLabel(alert.type)}
                      </span>
                      {alertOverdue && (
                        <span className="px-2 py-1 rounded-full text-xs font-medium bg-red-100 text-red-800">
                          En retard
                        </span>
                      )}
                    </div>
                    <p className="text-gray-600 mb-3">{alert.message}</p>
                    
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-gray-600 mb-4">
                      <div>
                        <span className="font-medium">Assigné à:</span> {alert.assignedTo}
                      </div>
                      <div>
                        <span className="font-medium">Département:</span> {alert.department}
                      </div>
                      <div>
                        <span className="font-medium">Créé le:</span> {new Date(alert.date).toLocaleDateString('fr-FR')}
                      </div>
                      <div>
                        <span className="font-medium">Échéance:</span> 
                        <span className={alertOverdue ? 'text-red-600 font-semibold' : ''}>
                          {new Date(alert.dueDate).toLocaleDateString('fr-FR')}
                        </span>
                      </div>
                    </div>
                    
                    {alert.actions && alert.actions.length > 0 && (
                      <div className="flex flex-wrap gap-2 mb-3">
                        {alert.actions.slice(0, 3).map((action, index) => (
                          <button
                            key={index}
                            onClick={() => handleAlertAction(alert.id, action)}
                            className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-xs hover:bg-blue-200 transition-colors"
                          >
                            {action}
                          </button>
                        ))}
                      </div>
                    )}
                    
                    {alert.relatedDocuments && alert.relatedDocuments.length > 0 && (
                      <div className="flex items-center space-x-2 text-xs text-gray-500">
                        <FileText className="w-3 h-3" />
                        <span>{alert.relatedDocuments.length} document(s) lié(s)</span>
                      </div>
                    )}
                  </div>
                </div>
                
                <div className="flex items-center space-x-2 ml-4">
                  <button
                    onClick={() => handleAlertAction(alert.id, 'view')}
                    className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg"
                    title="Voir détails"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleAlertAction(alert.id, 'resolve')}
                    className="p-2 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg"
                    title="Marquer comme résolu"
                  >
                    <Check className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleAlertAction(alert.id, 'archive')}
                    className="p-2 text-gray-400 hover:text-orange-600 hover:bg-orange-50 rounded-lg"
                    title="Archiver"
                  >
                    <Archive className="w-4 h-4" />
                  </button>
                  <div className="relative">
                    <button className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-50 rounded-lg">
                      <MoreVertical className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {filteredAlerts.length === 0 && (
        <div className="text-center py-16 bg-white rounded-xl shadow-sm border border-gray-100">
          <Bell className="w-16 h-16 text-gray-400 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-gray-900 mb-2">Aucune alerte trouvée</h3>
          <p className="text-gray-600 mb-6">Aucune alerte ne correspond à vos critères de recherche</p>
          <button
            onClick={() => {
              setSearchTerm('');
              setFilterPriority('all');
              setFilterType('all');
              setFilterStatus('active');
            }}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Réinitialiser les filtres
          </button>
        </div>
      )}

      {/* Create Alert Modal */}
      <CreateAlertModal
        isOpen={showCreateModal}
        onClose={() => setShowCreateModal(false)}
        onSubmit={(formData) => {
          const newAlert = {
            id: Date.now(),
            ...formData,
            status: 'active',
            date: new Date().toISOString(),
            createdBy: 'Utilisateur',
            autoGenerated: false,
            actions: ['Traiter', 'Assigner', 'Reporter'],
            relatedDocuments: []
          };
          setAlerts([newAlert, ...alerts]);
          setShowCreateModal(false);
        }}
      />
    </div>
  );
};

export default HRAlertsPage;